# Config file for automatic testing at travis-ci.com
os: linux
cache: pip

language: python
python:
  - nightly
  - 3.9
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
   - pip3 install -U pytest pytest-cov codecov tox
   - pip3 install -U .

# Command to run tests, e.g. python setup.py test
script: tox

matrix:
  allow_failures:
    - python: nightly

after_success: codecov

notifications:
  email:
    on_success: never
    on_failure: change
